/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_haydar_filescannercore_FileScannerJni */

#ifndef _Included_io_haydar_filescanner_FileScannerJni
#define _Included_io_haydar_filescanner_FileScannerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_haydar_filescannercore_FileScannerJni
 * Method:    scanDirs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jobject JNICALL Java_io_haydar_filescanner_FileScannerJni_scanDirs
  (JNIEnv *, jclass, jstring);
/*
 * Class:     io_haydar_filescanner_FileScannerJni
 * Method:    scanFiles
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_io_haydar_filescanner_FileScannerJni_scanFiles
        (JNIEnv *, jclass, jstring,jstring);


/*
 * Class:     io_haydar_filescanner_FileScannerJni
 * Method:    scanUpdateDirs
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_io_haydar_filescanner_FileScannerJni_scanUpdateDirs
        (JNIEnv *, jclass, jstring);

/*
 * Class:     io_haydar_filescanner_FileScannerJni
 * Method:    getFileLastModifiedTime
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_haydar_filescanner_FileScannerJni_getFileLastModifiedTime
        (JNIEnv *, jclass, jstring);






void doScannerDirs(JNIEnv *env, char *path) ;
void doScannerFiles(JNIEnv *env, char *path,char *type);
void doScannerUpdateDirs(JNIEnv *env, char *path);
void init(JNIEnv *pEnv) ;
void finish(JNIEnv *env);

#ifdef __cplusplus
}
#endif
#endif
